[package]
name = "link_o_matic"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
owo-colors = "4"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
